import { CommonLocators as C } from '../common/common.locators.js';

export const ProjectLocators = {
  loadingProjects: `//div[text()='Loading Projects']`,
  createProjectBtn: `[data-testid="projects.list.create"]`,
  projectTitle: `[data-testid="projects.list.create-drawer.name"]`,
  projectDescription: `[placeholder='Add description to the project']`,
  projectTag: C.tagsInput,
  projectCreate: `[data-testid="projects.list.create-drawer.submit"] button`,
  projectCreateFL: `//span[text()='New Project']`,
  saveChangesButton: `[data-testid="projects.list.create-drawer.submit"] button`,
  projectUpdatedToast: `.go3958317564`,
  projectEditButton: `role=menuitem[name="Edit"]`,
  projectDeleteButton: `role=menuitem[name="Delete"]`,
  projectDeleteConfirmInput: `input[placeholder="Type DELETE to confirm"]`,
  projectDeleteConfirmation: `//span[text()='Delete Project']`,
  projectDeleted: `//*[contains(text(),'Sample Project')]`,
  backToProjectList: `(//span[span[text()='Test Manager']])[1]`,
  projectListPage: `//h5[text()='Projects']`,
  backOnProjectPageCustom: `//span[a[span[text()='Projects']]]`,
  backOnProjectPageFromFieldPage: `(//span[normalize-space(text())='Projects'])[2]`,
  searchProject: `testid:projects.list.search`,
  createdProject: (name: string) => `//a[text()='${name}']`,
  createdProjectTC: (name: string) => `//span[text()='${name}']`,
  createdProjectAutomation: (name: string) => `//span[text()='${name}']`,
  createdProjectNameInTC: (name: string) => `(//span[text()='${name}'])[1]`,
  createdProjectNameBulkEdit: (name: string) => `(//span[text()='${name}'])[2]`,
  projectTripleDotButton: (name: string) =>
    `[data-testid="projects.list.row"]:has(a:text-is("${name}")) [data-testid="projects.list.row-actions"]`,
} as const;
