export const ProjectLocators = {
  loadingProjects: `//div[text()='Loading Projects']`,
  newProjectCta: `(//button[@aria-haspopup='true'])[1]`,
  createProjectCta: `//div[text()='Create new']`,
  newProjectCtaOverlay: `//span[text()='Create Project']`,
  projectTitle: `input[placeholder='Enter project name']`,
  projectDescription: `textarea[placeholder='Add description to the project']`,
  projectTag: `input[placeholder='Add Tags separated by enter']`,
  projectCreate: `//span[text()='Create']`,
  projectCreateFL: `//span[text()='New Project']`,
  saveChangesButton: `//span[text()='Save Changes']`,
  projectUpdatedToast: `.go3958317564`,
  projectEditButton: `//span[text()='Edit']`,
  projectDeleteButton: `//span[text()='Delete']`,
  projectDeleteConfirmInput: `//input[@aria-label="Search"]`,
  projectDeleteConfirmation: `//span[text()='Delete Project']`,
  projectDeleted: `//*[contains(text(),'Sample Project')]`,
  backOnProjectPage: `//h5[text()='Projects']`,
  backOnProjectPageCustom: `//span[a[span[text()='Projects']]]`,
  backOnProjectPageFromFieldPage: `(//span[normalize-space(text())='Projects'])[2]`,
  searchProject: `//input[@aria-label='Search Projects']`,
  createdProject: (name: string) => `//a[text()='${name}']`,
  createdProjectTC: (name: string) => `//span[text()='${name}']`,
  createdProjectAutomation: (name: string) => `//span[text()='${name}']`,
  createdProjectNameInTC: (name: string) => `(//span[text()='${name}'])[1]`,
  createdProjectNameBulkEdit: (name: string) => `(//span[text()='${name}'])[2]`,
  projectTripleDotButton: (name: string) => `//div[div[div[a[text()='${name}']]]]//div[2]//button`,
} as const;
