import { CommonLocators as C } from '../common/common.locators.js';

export const ProjectLocators = {
  loadingProjects: `//div[text()='Loading Projects']`,
  createProjectBtn: `//button[.//span[text()='Create Project']]`,
  projectTitle: `input[placeholder='Enter project name']`,
  projectDescription: `[placeholder='Add description to the project']`,
  projectTag: C.tagsInput,
  projectCreate: C.createSpan,
  projectCreateFL: `//span[text()='New Project']`,
  saveChangesButton: `//span[text()='Save Changes']`,
  projectUpdatedToast: `.go3958317564`,
  projectEditButton: C.editSpan,
  projectDeleteButton: C.deleteSpan,
  projectDeleteConfirmInput: `//input[@aria-label="Search"]`,
  projectDeleteConfirmation: `//span[text()='Delete Project']`,
  projectDeleted: `//*[contains(text(),'Sample Project')]`,
  backToProjectList: `(//span[span[text()='Test Manager']])[1]`,
  projectListPage: `//h5[text()='Projects']`,
  backOnProjectPageCustom: `//span[a[span[text()='Projects']]]`,
  backOnProjectPageFromFieldPage: `(//span[normalize-space(text())='Projects'])[2]`,
  searchProject: `//input[@aria-label='Search Projects']`,
  createdProject: (name: string) => `//a[text()='${name}']`,
  createdProjectTC: (name: string) => `//span[text()='${name}']`,
  createdProjectAutomation: (name: string) => `//span[text()='${name}']`,
  createdProjectNameInTC: (name: string) => `(//span[text()='${name}'])[1]`,
  createdProjectNameBulkEdit: (name: string) => `(//span[text()='${name}'])[2]`,
  projectTripleDotButton: (name: string) => `//div[div[div[a[text()='${name}']]]]//div[2]//button`,
} as const;
