export const TestRunLocators = {
  createTestRunCta: `//button[contains(.,'Create Test Run')]`,
  createTestRunButton: `//button[contains(.,'Create Test Run')]`,
  createTestPlanNextCta: `//span[text()='Next']`,
  addTcTestRunCta: `//span[text()='Add Test Cases']`,
  saveTestRunCta: `//button[contains(.,'Create Test Run')]`,
  testRunTitle: `input[placeholder='Enter Test Run name']`,
  testRunDescription: `textarea[placeholder='Add description to the Test Run']`,
  testRunTag: `input[placeholder='Add Tags separated by enter']`,
  nextCtaForTP: `//span[text()='Next']`,
  missingMsgTR: `//span[text()='Missing Assignee, Configurations']`,
  addConfigCtaTP: `//div[text()='Add a Configuration']`,
  selectConfigCheck: `//label[.//input[starts-with(@id, 'select-checkbox')]]`,
  selectConfigButton: `//span[text()='Set Configuration']`,
  applyConfiguration: `//span[text()='Apply']`,
  selectConfigCtaConfPopup: `(//span[text()='Select Configuration'])[2]`,
  selectAssigneeTRPageButton: `(//span[text()='Select Assignee'])[2]`,
  selectAssigneeTRPageButton1: `//span[text()='Select Assignee']`,
  selectAssignee: `(//span[@class='Item__TextContainer-sc-y6iv6t-3 bvbgsO'])[1]`,
  testRunNav: `//*[@role='tab' and contains(.,'Test Runs')]`,
  selectAllCheckboxInTpTestcase: `//input[@id='all' and @type='checkbox']`,
  selectAllCheckboxInTrInstances: `(//input[@class='Checkbox__StyledCheckbox-sc-1ga3qj3-0 cZZRyo'])[1]`,
  updateTestcaseInTestRun: `(//span[text()='Update'])[1]`,
  selectConfigInTRPage: `//label[.//input[starts-with(@id, 'select-checkbox')]]`,
  selectInstancesInBulk: `//input[@type='checkbox']`,
  backtoTestRunList: `//span[text()='Test Run']`,
  backtoTestRunListPage: `//span[text()="Test Run"]`,
  historyExecutionNav: `//span[text()='Runs']`,
  editCtaInsideTR: `//span[text()='Edit']`,
  deleteInsideTR: `//span[text()='Delete']`,
  deleteTestRunCta: `//span[text()='Delete Test Run']`,
  testrunDeleteButton: `//span[text()='Delete']`,
  setTPClose: `//div[text()='Set as ']`,
  setTPActive: `//span[text()='Set as ']`,
  duplicateTestRun: `//span[text()='Duplicate Test Run']`,
  viewDropdown: `//span[contains(text(),'View:')]`,
  viewClosedTP: `//span[text()='Closed']`,
  viewActiveTR: `//span[text()='Active']`,
  editTR: `//span[text()='Edit Test Run']`,
  addTcInTR: `//span[text()='Add Test Cases']`,
  archiveTestRun: `//span[contains(text(),'Set as Archive')]`,
  archivedTestRun: `//span[text()='Archived']`,
  activeTestRunFromList: `//span[text()='Set as Active']`,
  activeTestRun: `//span[text()='Active']`,
  tcStatusPassed: `//div[span[text()='Passed']]`,
  tcStatusPassedButton: `//span[text()='Passed']`,
  tcStatusPassedInstancesPageBulk: `//div[text()='Passed']`,
  tcStatusFailed: `//div[span[text()='Failed']]`,
  tcStatusFailedSdk: `//span[span[text()='Failed']]`,
  tcStatusSkip: `//div[span[text()='Skipped']]`,
  tcStatusSkipButton: `//span[text()='Skipped']`,
  tcStatusNotStarted: `(//span[text()='Not Started'])`,
  testRunStatusDropdown: `(//span[text()='In Progress'])[1]`,
  testRunStatusPassed: `(//span[text()='Passed'])[2]`,
  manualRunRemark: `//span[@aria-label='Not verified on LambdaTest']`,
  runTestInstances: `//span[text()='Run Test Instances']`,
  bulkAssigneeDropdown: `//span[text()='Set Assignee']`,
  bulkSelectAssignee: `(//span[@class='Box-sc-g0xbh4-0 avjpQ'])[1]`,
  bulkStatus: `(//span[text()='Not Started'])[2]`,
  bulkStatusDropdown: `//span[text()='Set Status']`,
  searchFieldInLinkProject: `//input[@name='Search']`,
  testplanBackButton: `//span[text()='Test Plans']`,
  createdTestrunAppear: (name: string) => `//a[text()="${name}"]`,
  createdTestrunAppearDashboard: (name: string) => `//span[text()="${name}"]`,
  testrunStepInstances: (name: string) => `(//span[text()="${name}"])`,
  createdTestrunAppearInstancesPage: (name: string) => `//span[text()="${name}"]`,
  duplicateTestRunByName: (name: string) => `//span[text()="Copy of ${name} 1"]`,
  testrunNavigation: (name: string) => `(//span[text()='${name}'])[1]`,
  duplicateTestRunNavigation: (name: string) => `(//span[text()="Copy of ${name} 1"])[1]`,
  createdTestrunOpenMenu: (name: string) => `//a[normalize-space(text())='${name}']//ancestor::div[contains(@class,'flex justify-between')]//button`,
  instanceStatusDropdown: () => `(//span[text()='Not Started'])[2]`,
  instanceStatusDropdownAfter: () => `(//span[text()='Not Started'])[1]`,
  testcaseButtonsOnInstancesPage: (title: string) => `//a[text()='${title}']/following::span[text()='Not Started']`,
  testcaseStatusInstancesPage: (title: string) => `//a[text()='${title}']/following::span[text()='Not Started']`,
  markStatusButtonForTestcase: (name: string) => `//div[contains(@class,'tm-flex-row')][.//span[contains(normalize-space(.),'${name}')]]//button[.//span[normalize-space(text())='Mark Status']]`,
  testStepsStatus: (status: string) => `//p[text()='${status}']/following::span[text()='Mark Status']`,
  testStepsStatusSdk: (status: string) => `//div[div[div[span[text()='${status}']]]]//button`,
  testStepsStatusCollapse: (status: string) => `(//div[div[div[div[span[text()='${status}']]]]]//button)[4]`,
  tcStatusSdk: (status: string) => `(//div[div[div[div[span[text()='${status}']]]]//button)[2]`,
} as const;
