import { CommonLocators as C } from '../common/common.locators.js';

export const TestCaseLocators = {
  createTestcaseCta: `//span[text()='Add Test Case']`,
  createTestcaseByField: `//span[text()='Add Test Case']`,
  createTestcaseByInputField: `input[placeholder='Type your test case title and press enter']`,
  createTestcaseByGrid: `input[placeholder="Type your test case title and press enter"]`,
  searchTcInput: `//input[@placeholder='Search by Test Case ID or Title']`,
  selectFunctionalTestType: `//span[text()='Functional']`,
  selectTestType: `//span[starts-with(@id, 'selectItem-') and text()='{{type}}']`,
  selectAutomatedAutomationStatus: `//span[starts-with(@id, 'selectItem-') and text()='Automated']`,
  selectHighTestPriority: `//span[starts-with(@id, 'selectItem-') and text()='{{priority}}']`,
  selectOpenTestStatus: `//span[starts-with(@id, 'selectItem-') and text()='Live']`,
  attachmentInTestcase: `#fileInput`,
  verifyAttachmentInTestcase: `//span[text()='sampleexample.txt']`,
  stepNav: `//span[text()='Test steps']`,
  createStep: `//p[@data-placeholder='Enter Step Description']`,
  addStepOutout: `//p[@data-placeholder='Enter Step Outcome']`,
  aiButton: `//span[text()='Generate with AI']`,
  createStepCta: `//button[@id="new-step-manual"]`,
  openMenu: C.openMenuButton,
  verifyAiTeststep: `(//div[@class='reactjs-tiptap-editor'])[3]`,
  attachmentInTeststep: `(//button//*[local-name()='svg' and contains(@class,'lucide-image-up')])[1]`,
  attachmentInTeststepUpload: `(//button[text()='Upload'])[2]`,
  verifyAttachmentInTeststep: `//span[text()='Screenshot0.png']`,
  saveTestCase: `//span[contains(text(), 'Save Changes')]`,
  saveTestCaseCommitMessage: `(//span[contains(text(), 'Save Changes')])[2]`,
  testcaseDeleteButton: C.deleteSpan,
  testcaseDeleteOpenMenu: `(//button[@data-component='IconButton' and @aria-haspopup='true'])[1]`, // Need to update this 
  testcaseDeleteConfirmation: C.deleteSpan,
  saveTestStep: `//span[contains(text(), 'Save Changes')]`,
  backFromEditTC: `//span[text()='Test details']`,
  testcaseBreadcrumb: `(//span[text()='Test Manager']//ancestor::button//following-sibling::div//button)[1]`,
  tcDiscard: `//span[text()='Discard Changes']`,
  tcId: `//span[contains(text(),'#TC-')]`,
  tcInput: `(//span[contains(.,'TC-')])[1]`,
  addTagTc: `//input[@placeholder='Add Tags separated by enter']`,
  addTagTcInputField: `//input[@placeholder='Add Tags separated by enter']`,
  addTagFieldTc: `//input[@placeholder='Type to add a tag']`,
  selectAllCheckbox: `(//input[@aria-checked="true"])[3]`,
  selectTestcaseTestcasePage: `#all`,
  selectSingleTestcase: `(//input[@type='checkbox'])[2]`,
  threeDots: `(//span[@class='ant-tree-title']//div[@role='button']//div[@class='cursor-pointer'])[2]`,
  typeDropdownTestcaseStage: `//span[text() = 'Type']//following-sibling::div//button`,
  automationDropdownTestcaseStage: `//span[text() = 'Automation Status']//following-sibling::div//button`,
  priorityDropdownTestcaseStage: `//span[text() = 'Priority']//following-sibling::div//button`,
  statusDropdownTestcaseStage: `//span[text() = 'Status']//following-sibling::div//button`,
  linkAllCheckStage: `(//*[@class='Checkbox__StyledCheckbox-sc-1ga3qj3-0 cZZRyo'])[1]`,
  linkSingleProjectStage: `(//*[@class='Checkbox__StyledCheckbox-sc-1ga3qj3-0 cZZRyo'])[2]`,
  automationStatusManual: `//span[text()='Not Automated']`,
  automationStatusAutomated: `//span[text()='Automated']`,
  testcasesCountInsideTestcasesPage: `//h5[normalize-space()='All Test Cases']/following-sibling::span`,
  allTestCasesCount: `//h5[text()='All Test Cases']/following-sibling::*[1]`,
  manualTestingTag: `//span[text()='manual']`,
  automationTestingTag: `//span[text()='automation']`,
  selectionBanner: `//p[text()=' Test Cases are selected.']`,
  clearSelection: `//span[text()='Clear Selection']`,
  runTestCase: `//button[@aria-labelledby="Run Test Case"]`,
  createdTC: (title: string) => `//a[text()='${title}']`,
  selectTC: (title: string) => `//span[text()='${title}']`,
  createdTCEditor: (title: string) => `//h5[text()='${title}']`,
  createdTeststep: (title: string) => `//p[text()='${title}']`,
  createdTcTag: (tag: string) => `//div[text()='${tag}']`,
  // Scenario type locators
  manualStepDropdown: `(//span[text()='Manual Test Steps'])[1]`, // Need to update this 
  scenarioTypeDropdown: `//span[text()='BDD Scenarios']`,
  scenarioTypeSelected: `//span[text()='Behaviour Driven Development']`,
  scenarioField: `(//div[@class='view-lines monaco-mouse-cursor-text'])[last()]`,
  addScenarioCta: `(//span[text()='Add scenario'])[2]`,
  addScenarioButton: `(//span[text()='Add scenario'])[1]`, // Need to update this 
  scenarioCount: `(//span[@data-component='trailingVisual']//span[@aria-hidden='true'])[2]`, // Need to update this 
  scenarioItems: `//span[@aria-label='Delete Scenario']`,
  scenarioDuplicate: `//*[name()='svg' and contains(@class, 'octicon-duplicate')]`,
  scenarioDelete: `//span[@aria-label='Delete Scenario']`,
  scenarioDeleteConfirmation: C.deleteSpan,
  scenarioAccept: `//span[text()='Accept']`,
  scenarioReject: `//span[text()='Reject']`,
} as const;
