export const NavigationLocators = {
  hamburgerSidebar: `//button[@class=" ltch-top-nav-hamburger-menu"]`,
  projectSidebar: `//span[@class="ltch-product-name"]`,
  projectList: `(//span[span[text()='Test Manager']])[1]`,
  tmsSidebar: `//span[@class='ltch-product-name' and text()='Test Manager']`,
  tmsVisible: `//span[text()='Test Manager']`,
  tmsCtaFalcon: `//div[@aria-label='Test Manager']`,
  tmsCtaRealDevice: `//div[@id="test-case-manager"]`,
  sidebarSettings: `//span[text()='Settings']`,
  automationSidebar: `//span[text()='Automation']`,
  kaneaiSidebar: `(//a[@aria-label="KaneAI"])`,
  moduleSidebar: `//h5[text()="Modules"]`,
  testCaseNav: `//span[text()='Test Cases']`,
  testRunNav: `//span[text()='Test Runs']`,
  buildNav: `//a[text()='Builds']`,
  insightPageNav: `//a[span[text()='Insights']]`,
  settingStage: `//a[text()='System Fields']`,
  reportsTab: `//a[span[text()='Reports']]`,
} as const;
