export const FolderLocators = {
  createFolderMainCta: `//button[contains(.,'Create New Folder')]`,
  createFolderButton: `//button[contains(.,'Create New Folder')]`,
  folderTitleField: `//input[@placeholder='Enter root folder name']`,
  folderNameInput: `//input[@placeholder='Enter folder name']`,
  createFolderSubmit: `//button[text()='Create']`,
  createSubFolderButton: `//button[@aria-label='Create subfolder']`,
  createSubFolderForFolder: (name: string) => `//span[text()='${name}']/../following-sibling::button/button[1]`,
  createAnotherFolder: `//*[contains(@class,'octicon octicon-plus')]//parent::button`,
  subFolderTitleField: `//input[@placeholder='Enter folder name']`,
  defaultFolderName: `(//span[text()='Untitled'])[1]`,
  deleteFolderConfirmation: `//span[text()='Delete']`,
  deleteFolderButton: `//span[text()='Delete Folder']`,
  deleteFolderConfirmInput: `//input[@placeholder='Type DELETE to confirm']`,
  deleteFolderConfirm: `//button[text()='Delete']`,
  renameFolder: `//span[text()='Rename']`,
  renameFolderButton: `//span[text()='Rename']`,
  saveFolderButton: `//button[text()='Save']`,
  deleteFolder: `//div[contains(@class,'Overlay__StyledOverlay')]//span[text()='Delete']`,
  expandFolder: `//span[@aria-label='caret-down']`,
  addFolderCta: `(//button//*[name()='svg' and contains(@class, 'octicon-plus')])[2]`,
  banner: `//*[contains(@class,'octicon')]/following-sibling::p`,
  selectionViaHyperLink: `//*[contains(@class,'octicon')]/following-sibling::p/button`,
  bulkActionCta: `(//span[text()='More'])[2]`,
  bulkActionsButton: `//button[text()='Bulk Actions']`,
  bulkActionCopy: `//span[text()='Copy']`,
  bulkActionMove: `//span[text()='Move']`,
  copyTestCasesButton: `//span[text()='Copy Test Cases']`,
  moveTestCasesButton: `//span[text()='Move Test Cases']`,
  selectFolderDropdown: `//button[text()='Select Folder']`,
  copyTestCasesConfirm: `//button[text()='Copy']`,
  moveTestCasesConfirm: `//button[text()='Move']`,
  testCasesCopiedSuccess: `//div[text()='Test cases copied successfully']`,
  testCasesMovedSuccess: `//div[text()='Test cases moved successfully']`,
  testCaseCheckbox: `//input[@type='checkbox']`,
  targetOldFolder: `(//span[text()='Untitled'])[10]`,
  copyButton: `//span[text()='Copy']`,
  moveButton: `//span[text()='Move']`,
  moveTestcasesToast: `//div[text()='Test cases already present in the target folder']`,
  closeMoveTc: `//div[@role='button']//*[name()='svg' and contains(@class, 'octicon-x')]`,
  verifyCopiedTc: `(//a[text()='Verify phone number update'])[2]`,
  verifyMovedTc: `//a[text()='Verify phone number update']`,
  folderButtons: (name: string) => `//span[text()='${name}']/following::div[@role='button']`,
  folderButtonsEdit: (name: string) => `//span[text()='${name}']//ancestor::div[contains(@class,'lt-tooltip-trigger')]//div`,
  renameFolderInput: (name: string) => `(//input[@value='${name}'])[1]`,
  folderNameInNav: (name: string) => `//span[text()='${name}']`,
  folderNameInSidebar: (name: string) => `(//span[text()='${name}'])[1]`,
  folderNameBulkEdit: (name: string) => `(//span[text()='${name}'])[1]`,
  folderTreeItem: (name: string) => `//div[contains(@class,'ant-tree-treenode')]//span[text()='${name}']/ancestor::div[contains(@class,'ant-tree-treenode-draggable')]`,
  folderDragHandle: (name: string) => `//span[text()='${name}']/ancestor::div[contains(@class,'ant-tree-treenode')]//span[contains(@class,'ant-tree-draggable-icon')]`,
  folderTestCaseCount: (name: string) => `//span[@title='${name}']//following-sibling::span`,
  folderExpandIcon: (name: string) => `//span[text()='${name}']/ancestor::div[contains(@class,'ant-tree-treenode')]//span[contains(@class,'ant-tree-switcher')]`,
  folderCollapseIcon: (name: string) => `//span[text()='${name}']/ancestor::div[contains(@class,'ant-tree-treenode')]//span[contains(@class,'ant-tree-switcher')]`,
  subfolderUnderParent: (parent: string, child: string) => `//span[text()='${parent}']/ancestor::div[contains(@class,'ant-tree-treenode')]//following-sibling::div[contains(@class,'ant-tree-treenode')]//span[text()='${child}']`,
  createdFolder: (name: string) => `//span[text()='${name}']`,
  folderOptionsMenu: (name: string) => `//span[text()='${name}']/../following-sibling::button/button[2]`,
  selectFolder: (name: string) => `//span[text()='${name}']`,
  folderBreadcrumb: (name: string) => `//nav//span[text()='${name}']`,
} as const;
