import { CommonLocators as C } from '../common/common.locators.js';

export const FolderLocators = {
  createFolderMainCta: `//nav[@aria-label='Folders Group']//button[.//*[contains(@class,'octicon-plus')]]`,
  createFolderButton: `//nav[@aria-label='Folders Group']//button[.//*[contains(@class,'octicon-plus')]]`,
  folderTitleField: `//input[@placeholder='Enter root folder name']`,
  folderNameInput: `//input[@placeholder='Enter folder name']`,
  createFolderSubmit: `//button[text()='Create']`,
  createSubFolderButton: `//button[@aria-label='Create subfolder']`,
  createSubFolderForFolder: (name: string) => `//span[@title='${name}']/ancestor::div[contains(@class,'ant-tree-treenode')]//*[@id='add-sub-folder']`,
  createAnotherFolder: `//*[contains(@class,'octicon octicon-plus')]//parent::button`,
  subFolderTitleField: `//input[@placeholder='Enter folder name']`,
  defaultFolderName: `(//span[text()='Untitled'])[1]`,
  deleteFolderConfirmation: C.deleteSpan,
  deleteFolderButton: `//li//*[text()='Delete']`,
  deleteFolderConfirmInput: C.typeDeleteInput,
  deleteFolderConfirm: C.deleteConfirmButton,
  renameFolder: `//li//*[text()='Rename']`,
  renameFolderButton: `//li//*[text()='Rename']`,
  saveFolderButton: `//button[text()='Save']`,
  deleteFolder: `//li//*[text()='Delete']`,
  expandFolder: `//span[@aria-label='caret-down']`,
  addFolderCta: `//nav[@aria-label='Folders Group']//button[.//*[contains(@class,'octicon-plus')]]`,
  banner: `//*[contains(@class,'octicon')]/following-sibling::p`,
  selectionViaHyperLink: `//*[contains(@class,'octicon')]/following-sibling::p/button`,
  bulkActionCta: `//button[@id='bulk-automate-button']/following-sibling::*//button`,
  bulkActionsButton: `//button[@id='bulk-automate-button']/following-sibling::*//button`,
  bulkActionCopy: `//*[@role='menuitem'][.//*[text()='Copy']]`,
  bulkActionMove: `//*[@role='menuitem'][.//*[text()='Move']]`,
  copyTestCasesButton: `//*[@role='menuitem'][.//*[text()='Copy']]`,
  moveTestCasesButton: `//*[@role='menuitem'][.//*[text()='Move']]`,
  selectFolderDropdown: `//nav[.//*[text()='Copy Test Cases'] or .//*[text()='Move Test Cases']]`,
  copyTestCasesConfirm: `//nav[.//*[text()='Copy Test Cases']]//button[.//*[text()='Copy']]`,
  moveTestCasesConfirm: `//nav[.//*[text()='Move Test Cases']]//button[.//*[text()='Move']]`,
  testCasesCopiedSuccess: `//*[contains(text(),'copied')]`,
  testCasesMovedSuccess: `//*[contains(text(),'moved')]`,
  testCaseCheckbox: `//input[@type='checkbox']`,
  targetOldFolder: `(//span[text()='Untitled'])[10]`,
  copyButton: `//span[text()='Copy']`,
  moveButton: `//span[text()='Move']`,
  moveTestcasesToast: `//div[text()='Test cases already present in the target folder']`,
  closeMoveTc: `//div[@role='button']//*[name()='svg' and contains(@class, 'octicon-x')]`,
  verifyCopiedTc: `(//a[text()='Verify phone number update'])[2]`,
  verifyMovedTc: `//a[text()='Verify phone number update']`,
  folderButtons: (name: string) => `//span[text()='${name}']/following::div[@role='button']`,
  folderButtonsEdit: (name: string) => `//span[text()='${name}']//ancestor::div[contains(@class,'lt-tooltip-trigger')]//div`,
  renameInput: `//div[contains(@class,'ant-tree-treenode')]//input[contains(@class,'ant-input')]`,
  renameFolderInput: (name: string) => `(//input[@value='${name}'])[1]`,
  folderNameInNav: (name: string) => `//span[text()='${name}']`,
  folderNameInSidebar: (name: string) => `(//span[text()='${name}'])[1]`,
  folderNameBulkEdit: (name: string) => `(//span[text()='${name}'])[1]`,
  folderTreeItem: (name: string) => `//div[contains(@class,'ant-tree-treenode')]//span[text()='${name}']/ancestor::div[contains(@class,'ant-tree-treenode')]`,
  folderDragHandle: (name: string) => `//span[@title='${name}']/ancestor::div[contains(@class,'ant-tree-treenode')]//img[@alt='folder']`,
  folderTestCaseCount: (name: string) => `//span[@title='${name}']/following-sibling::span`,
  folderExpandIcon: (name: string) => `//span[@title='${name}']/ancestor::div[contains(@class,'ant-tree-treenode')]/span[contains(@class,'ant-tree-switcher')]`,
  folderCollapseIcon: (name: string) => `//span[@title='${name}']/ancestor::div[contains(@class,'ant-tree-treenode')]/span[contains(@class,'ant-tree-switcher')]`,
  subfolderUnderParent: (parent: string, child: string) => `//span[text()='${parent}']/ancestor::div[contains(@class,'ant-tree-treenode')]//following-sibling::div[contains(@class,'ant-tree-treenode')]//span[text()='${child}']`,
  createdFolder: (name: string) => `//div[contains(@class,'ant-tree')]//span[@title='${name}']`,
  folderOptionsMenu: (name: string) => `//span[@title='${name}']/ancestor::div[contains(@class,'ant-tree-treenode')]//div[@aria-haspopup='true']`,
  selectFolder: (name: string) => `//nav[.//*[text()='Copy Test Cases'] or .//*[text()='Move Test Cases']]//span[@title='${name}']`,
  allTestCasesButton: `//div[@role='button'][@aria-label='All Test Cases']`,
  folderBreadcrumb: (name: string) => `//span[@title='${name}']`,
  // Cross-project copy/move panel locators
  copyMoveProjectDropdown: `//nav[.//*[text()='Copy Test Cases'] or .//*[text()='Move Test Cases']]//*[text()='Project']/../following-sibling::div/button`,
  filterProjectsInput: `input[placeholder='Filter Projects']`,
  projectOption: (name: string) => `//div[@role='option'][normalize-space()='${name}']`,
} as const;
